# specify language
language:
  - python

# specify python version(s)
python:
  - "3.4"
  - "2.7"

# install dependencies
install:
  - pip install -r requirements.txt

# run tests
script:
  - nosetests